# Generated by Django 2.2.6 on 2019-11-28 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_the_Company', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField()),
                ('Type', models.CharField(blank=True, max_length=20, null=True)),
                ('Indstry_sctr_Core', models.CharField(blank=True, max_length=10, null=True)),
                ('Indstry_sctr_consulting', models.CharField(blank=True, max_length=10, null=True)),
                ('Indstry_sctr_IT', models.CharField(blank=True, max_length=10, null=True)),
                ('Indstry_sctr_Finanace', models.CharField(blank=True, max_length=10, null=True)),
                ('Indstry_sctr_Govrnt', models.CharField(blank=True, max_length=10, null=True)),
                ('Indstry_sctr_Other', models.CharField(blank=True, max_length=100, null=True)),
                ('req_functional_areas_Red', models.CharField(blank=True, max_length=10, null=True)),
                ('req_functional_areas_Maintenance', models.CharField(blank=True, max_length=10, null=True)),
                ('req_functional_areas_Design', models.CharField(blank=True, max_length=10, null=True)),
                ('req_functional_areas_Production', models.CharField(blank=True, max_length=10, null=True)),
                ('req_functional_areas_RD', models.CharField(blank=True, max_length=10, null=True)),
                ('req_functional_areas_Others', models.CharField(blank=True, max_length=200, null=True)),
                ('req_functional_areas_Finance', models.CharField(blank=True, max_length=10, null=True)),
                ('VsnandInterest', models.CharField(blank=True, max_length=10, null=True)),
                ('PrsnName', models.CharField(blank=True, max_length=200, null=True)),
                ('PrsnDesignation', models.CharField(blank=True, max_length=200, null=True)),
                ('PrsnPhone', models.CharField(blank=True, max_length=200, null=True)),
                ('PrsnEmail', models.CharField(blank=True, max_length=200, null=True)),
                ('CGPA', models.CharField(blank=True, max_length=10, null=True)),
                ('XII_perc', models.CharField(blank=True, max_length=10, null=True)),
                ('X_perc', models.CharField(blank=True, max_length=200, null=True)),
                ('SpecialisationPG', models.CharField(blank=True, max_length=200, null=True)),
                ('Age_limits', models.CharField(blank=True, max_length=200, null=True)),
                ('Test_Written', models.CharField(blank=True, max_length=10, null=True)),
                ('Test_Aptitude', models.CharField(blank=True, max_length=10, null=True)),
                ('Test_Online', models.CharField(blank=True, max_length=10, null=True)),
                ('Test_Technical', models.CharField(blank=True, max_length=10, null=True)),
                ('Test_Others', models.CharField(blank=True, max_length=10, null=True)),
                ('GD', models.CharField(blank=True, max_length=20, null=True)),
                ('PITechnical', models.CharField(blank=True, max_length=10, null=True)),
                ('PIHR', models.CharField(blank=True, max_length=10, null=True)),
                ('PIOthers', models.CharField(blank=True, max_length=100, null=True)),
                ('ServiceAgreement', models.CharField(blank=True, max_length=100, null=True)),
                ('TrainingPeriod', models.CharField(blank=True, max_length=100, null=True)),
                ('AllStreamsBtech', models.CharField(blank=True, max_length=10, null=True)),
                ('AllStreamsIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('AllStreamsMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('AllStreamsIMD', models.CharField(blank=True, max_length=10, null=True)),
                ('CeraBtech', models.CharField(blank=True, max_length=10, null=True)),
                ('CeraMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('CeraIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('ChemBTech', models.CharField(blank=True, max_length=10, null=True)),
                ('ChemMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('CivilBtech', models.CharField(blank=True, max_length=10, null=True)),
                ('CivilIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('CivilMtech', models.CharField(blank=True, max_length=10, null=True)),
                ('ComputerBtech', models.CharField(blank=True, max_length=10, null=True)),
                ('ComputerIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('TricalBtech', models.CharField(blank=True, max_length=10, null=True)),
                ('TricalMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('TricalIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('TronicsBtech', models.CharField(blank=True, max_length=10, null=True)),
                ('TronicsMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('TronicsIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('MechBtech', models.CharField(blank=True, max_length=10, null=True)),
                ('MechMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('MechIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('MetaBtech', models.CharField(blank=True, max_length=10, null=True)),
                ('MetaMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('MetaIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('MinBtech', models.CharField(blank=True, max_length=10, null=True)),
                ('MinMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('MinIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('BioChemMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('BioChemIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('BioMedMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('BioMedIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('MSTMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('MSTIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('PharmaBtech', models.CharField(blank=True, max_length=10, null=True)),
                ('PharmaMTech', models.CharField(blank=True, max_length=10, null=True)),
                ('PharmaIDD', models.CharField(blank=True, max_length=10, null=True)),
                ('EngPhy', models.CharField(blank=True, max_length=10, null=True)),
                ('MNC', models.CharField(blank=True, max_length=10, null=True)),
                ('InC', models.CharField(blank=True, max_length=10, null=True)),
                ('CTC', models.CharField(blank=True, max_length=20, null=True)),
                ('In_Hand', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeavePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_choices', models.ManyToManyField(to='tpo.Choices')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
